version: '3.8'

services:
  app:
    build: .
    container_name: app
    depends_on:
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app

networks:
  app:
    driver: bridge
